### ISSUE TITLE
US-Register & Login

### ISSUE THREAD

**Issue by wokidoo** [philniko/group_15-SOEN341_Project_F24#21]
### Description
Users must be able to log into their accounts and be directed to a dashboard appropriate to an instructor or student, depending on the user's role.

### Acceptance Flow
1. User inputs name, email, password, and desired role in the registration page fields
2. user is directed to login page if registration was successful
3. User inputs email and password into their respective fields 
4. User presses the login button and credentials are validated 
5. User is directed to appropriate dashboard (Student or Instructor) if their credentials are valid 

### Acceptance Criteria
- [ ] Acceptance flow is respected
- [ ] Tasks are assigned and documented
- [ ] UI testing is implemented for all related pages

### Tasks
- [x] #1 
- [x] #12 
- [x] #13 
- [x] #14 
- [x] #15
- [x] #16 
- [x] #23 
- [x] #24
