### ISSUE TITLE
US-Register

### ISSUE THREAD

**Issue by wokidoo** [philniko/group_15-SOEN341_Project_F24#45]
### Description
Users must be able to register an account to log into the website

### Acceptance Flow
1. User navigates to the registration page
2. User inputs name, email, password, and desired role in the registration page fields
3. User presses the register button
4. User fields are validated
5. User information is added to the database
6. Successful registration message is posted
### Acceptance Criteria
- [x] Acceptance flow is respected
- [x] Tasks are assigned and documented
- [x] UI testing is implemented for all related pages

### Tasks

- [x] #13  
- [x] #16 
- [x] #17 
- [x] #26
