### ISSUE TITLE
US-Login

### ISSUE THREAD

**Issue by wokidoo** [philniko/group_15-SOEN341_Project_F24#46]
### Description
Users must be able to log into their accounts.

### Acceptance Flow
1. User navigates to login page
2. User inputs email and password
3. user presses the login button
4. User email and password are validated 
5. User is routed to appropriate dashboard
 
### Acceptance Criteria
- [ ] Acceptance flow is respected
- [ ] Tasks are assigned and documented
- [ ] UI testing is implemented for all related pages

### Tasks
- [x] #1 
- [x] #12  
- [x] #23 
- [x] #24
