### ISSUE TITLE
US-Instructor Dashboard

### ISSUE THREAD

**Issue by wokidoo** [philniko/group_15-SOEN341_Project_F24#47]
### Description
Users who log in as instructors are routed to the instructor dashboard where they can create groups and observe evaluations from students

### Acceptance Flow
1. User is directed to the instructor dashboard after logging in
2. user can navigate the dashboard and view created groups
3. User can create new groups 

### Acceptance Criteria
- [ ] Acceptance flow is respected
- [ ] Tasks are assigned and documented
- [ ] UI testing is implemented for all related pages

### Tasks

- [x] #14
